[package]
name = "rust-experiments"
version = "0.1.0"
authors = ["Michał W. Urbańczyk <mwu-tow@gazeta.pl>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile ="3.2.0"
