name: "CLI command"
on:
  workflow_dispatch:
    inputs:
      command:
        description: "Command to run"
        
jobs:
  main_job:
    runs-on:
      - macos-latest
    steps:
      - run: ${{ inputs.command }}
